package com.ezok.model;

import java.util.Date;

public class AdminInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_admin_info.ID
     *
     * @mbggenerated Sun Feb 16 19:16:26 CST 2014
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_admin_info.USER_NAME
     *
     * @mbggenerated Sun Feb 16 19:16:26 CST 2014
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_admin_info.PASSWORD
     *
     * @mbggenerated Sun Feb 16 19:16:26 CST 2014
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_admin_info.STATUS
     *
     * @mbggenerated Sun Feb 16 19:16:26 CST 2014
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_admin_info.ROLE
     *
     * @mbggenerated Sun Feb 16 19:16:26 CST 2014
     */
    private Integer role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_admin_info.CREATE_DATE
     *
     * @mbggenerated Sun Feb 16 19:16:26 CST 2014
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_admin_info.ID
     *
     * @return the value of tbl_admin_info.ID
     *
     * @mbggenerated Sun Feb 16 19:16:26 CST 2014
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_admin_info.ID
     *
     * @param id the value for tbl_admin_info.ID
     *
     * @mbggenerated Sun Feb 16 19:16:26 CST 2014
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_admin_info.USER_NAME
     *
     * @return the value of tbl_admin_info.USER_NAME
     *
     * @mbggenerated Sun Feb 16 19:16:26 CST 2014
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_admin_info.USER_NAME
     *
     * @param userName the value for tbl_admin_info.USER_NAME
     *
     * @mbggenerated Sun Feb 16 19:16:26 CST 2014
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_admin_info.PASSWORD
     *
     * @return the value of tbl_admin_info.PASSWORD
     *
     * @mbggenerated Sun Feb 16 19:16:26 CST 2014
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_admin_info.PASSWORD
     *
     * @param password the value for tbl_admin_info.PASSWORD
     *
     * @mbggenerated Sun Feb 16 19:16:26 CST 2014
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_admin_info.STATUS
     *
     * @return the value of tbl_admin_info.STATUS
     *
     * @mbggenerated Sun Feb 16 19:16:26 CST 2014
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_admin_info.STATUS
     *
     * @param status the value for tbl_admin_info.STATUS
     *
     * @mbggenerated Sun Feb 16 19:16:26 CST 2014
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_admin_info.ROLE
     *
     * @return the value of tbl_admin_info.ROLE
     *
     * @mbggenerated Sun Feb 16 19:16:26 CST 2014
     */
    public Integer getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_admin_info.ROLE
     *
     * @param role the value for tbl_admin_info.ROLE
     *
     * @mbggenerated Sun Feb 16 19:16:26 CST 2014
     */
    public void setRole(Integer role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_admin_info.CREATE_DATE
     *
     * @return the value of tbl_admin_info.CREATE_DATE
     *
     * @mbggenerated Sun Feb 16 19:16:26 CST 2014
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_admin_info.CREATE_DATE
     *
     * @param createDate the value for tbl_admin_info.CREATE_DATE
     *
     * @mbggenerated Sun Feb 16 19:16:26 CST 2014
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}