package com.ezok.model;

import java.util.Date;

public class CategoryInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_category_info.ID
     *
     * @mbggenerated Tue Apr 01 13:29:30 CST 2014
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_category_info.NO
     *
     * @mbggenerated Tue Apr 01 13:29:30 CST 2014
     */
    private String no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_category_info.NAME
     *
     * @mbggenerated Tue Apr 01 13:29:30 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_category_info.PRIORITY
     *
     * @mbggenerated Tue Apr 01 13:29:30 CST 2014
     */
    private Integer priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_category_info.STATUS
     *
     * @mbggenerated Tue Apr 01 13:29:30 CST 2014
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_category_info.PARENT_NO
     *
     * @mbggenerated Tue Apr 01 13:29:30 CST 2014
     */
    private String parentNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_category_info.STRUCT
     *
     * @mbggenerated Tue Apr 01 13:29:30 CST 2014
     */
    private String struct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_category_info.STRUCT_NAME
     *
     * @mbggenerated Tue Apr 01 13:29:30 CST 2014
     */
    private String structName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_category_info.CLICK_SUM
     *
     * @mbggenerated Tue Apr 01 13:29:30 CST 2014
     */
    private Integer clickSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_category_info.CREATE_DATE
     *
     * @mbggenerated Tue Apr 01 13:29:30 CST 2014
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_category_info.ID
     *
     * @return the value of tbl_category_info.ID
     *
     * @mbggenerated Tue Apr 01 13:29:30 CST 2014
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_category_info.ID
     *
     * @param id the value for tbl_category_info.ID
     *
     * @mbggenerated Tue Apr 01 13:29:30 CST 2014
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_category_info.NO
     *
     * @return the value of tbl_category_info.NO
     *
     * @mbggenerated Tue Apr 01 13:29:30 CST 2014
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_category_info.NO
     *
     * @param no the value for tbl_category_info.NO
     *
     * @mbggenerated Tue Apr 01 13:29:30 CST 2014
     */
    public void setNo(String no) {
        this.no = no == null ? null : no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_category_info.NAME
     *
     * @return the value of tbl_category_info.NAME
     *
     * @mbggenerated Tue Apr 01 13:29:30 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_category_info.NAME
     *
     * @param name the value for tbl_category_info.NAME
     *
     * @mbggenerated Tue Apr 01 13:29:30 CST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_category_info.PRIORITY
     *
     * @return the value of tbl_category_info.PRIORITY
     *
     * @mbggenerated Tue Apr 01 13:29:30 CST 2014
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_category_info.PRIORITY
     *
     * @param priority the value for tbl_category_info.PRIORITY
     *
     * @mbggenerated Tue Apr 01 13:29:30 CST 2014
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_category_info.STATUS
     *
     * @return the value of tbl_category_info.STATUS
     *
     * @mbggenerated Tue Apr 01 13:29:30 CST 2014
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_category_info.STATUS
     *
     * @param status the value for tbl_category_info.STATUS
     *
     * @mbggenerated Tue Apr 01 13:29:30 CST 2014
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_category_info.PARENT_NO
     *
     * @return the value of tbl_category_info.PARENT_NO
     *
     * @mbggenerated Tue Apr 01 13:29:30 CST 2014
     */
    public String getParentNo() {
        return parentNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_category_info.PARENT_NO
     *
     * @param parentNo the value for tbl_category_info.PARENT_NO
     *
     * @mbggenerated Tue Apr 01 13:29:30 CST 2014
     */
    public void setParentNo(String parentNo) {
        this.parentNo = parentNo == null ? null : parentNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_category_info.STRUCT
     *
     * @return the value of tbl_category_info.STRUCT
     *
     * @mbggenerated Tue Apr 01 13:29:30 CST 2014
     */
    public String getStruct() {
        return struct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_category_info.STRUCT
     *
     * @param struct the value for tbl_category_info.STRUCT
     *
     * @mbggenerated Tue Apr 01 13:29:30 CST 2014
     */
    public void setStruct(String struct) {
        this.struct = struct == null ? null : struct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_category_info.STRUCT_NAME
     *
     * @return the value of tbl_category_info.STRUCT_NAME
     *
     * @mbggenerated Tue Apr 01 13:29:30 CST 2014
     */
    public String getStructName() {
        return structName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_category_info.STRUCT_NAME
     *
     * @param structName the value for tbl_category_info.STRUCT_NAME
     *
     * @mbggenerated Tue Apr 01 13:29:30 CST 2014
     */
    public void setStructName(String structName) {
        this.structName = structName == null ? null : structName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_category_info.CLICK_SUM
     *
     * @return the value of tbl_category_info.CLICK_SUM
     *
     * @mbggenerated Tue Apr 01 13:29:30 CST 2014
     */
    public Integer getClickSum() {
        return clickSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_category_info.CLICK_SUM
     *
     * @param clickSum the value for tbl_category_info.CLICK_SUM
     *
     * @mbggenerated Tue Apr 01 13:29:30 CST 2014
     */
    public void setClickSum(Integer clickSum) {
        this.clickSum = clickSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_category_info.CREATE_DATE
     *
     * @return the value of tbl_category_info.CREATE_DATE
     *
     * @mbggenerated Tue Apr 01 13:29:30 CST 2014
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_category_info.CREATE_DATE
     *
     * @param createDate the value for tbl_category_info.CREATE_DATE
     *
     * @mbggenerated Tue Apr 01 13:29:30 CST 2014
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}