package com.ezok.model;

import java.util.Date;

public class NavInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_nav_info.ID
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_nav_info.NO
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    private String no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_nav_info.NAME
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_nav_info.URL
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_nav_info.SUMMARY
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    private String summary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_nav_info.NAV_DESC
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    private String navDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_nav_info.CATEGORY_NO
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    private String categoryNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_nav_info.CATEGORY_NAME
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    private String categoryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_nav_info.WEIBO_URL
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    private String weiboUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_nav_info.PROVINCE
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_nav_info.CITY
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_nav_info.WEIXIN_ACCOUNT
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    private String weixinAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_nav_info.WEIXIN_NAME
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    private String weixinName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_nav_info.ICON_URL
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    private String iconUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_nav_info.YX_EWM_URL
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    private String yxEwmUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_nav_info.WX_EWM_URL
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    private String wxEwmUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_nav_info.YIXIN_ACCOUNT
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    private String yixinAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_nav_info.YIXIN_NAME
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    private String yixinName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_nav_info.CREATE_DATE
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_nav_info.UPDATE_DATE
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_nav_info.PRIORITY
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    private Integer priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_nav_info.USERNAME
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_nav_info.STATUS
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_nav_info.CLICK_SUM
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    private Integer clickSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_nav_info.REMARK
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_nav_info.ID
     *
     * @return the value of tbl_nav_info.ID
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_nav_info.ID
     *
     * @param id the value for tbl_nav_info.ID
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_nav_info.NO
     *
     * @return the value of tbl_nav_info.NO
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_nav_info.NO
     *
     * @param no the value for tbl_nav_info.NO
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    public void setNo(String no) {
        this.no = no == null ? null : no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_nav_info.NAME
     *
     * @return the value of tbl_nav_info.NAME
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_nav_info.NAME
     *
     * @param name the value for tbl_nav_info.NAME
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_nav_info.URL
     *
     * @return the value of tbl_nav_info.URL
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_nav_info.URL
     *
     * @param url the value for tbl_nav_info.URL
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_nav_info.SUMMARY
     *
     * @return the value of tbl_nav_info.SUMMARY
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_nav_info.SUMMARY
     *
     * @param summary the value for tbl_nav_info.SUMMARY
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_nav_info.NAV_DESC
     *
     * @return the value of tbl_nav_info.NAV_DESC
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    public String getNavDesc() {
        return navDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_nav_info.NAV_DESC
     *
     * @param navDesc the value for tbl_nav_info.NAV_DESC
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    public void setNavDesc(String navDesc) {
        this.navDesc = navDesc == null ? null : navDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_nav_info.CATEGORY_NO
     *
     * @return the value of tbl_nav_info.CATEGORY_NO
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    public String getCategoryNo() {
        return categoryNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_nav_info.CATEGORY_NO
     *
     * @param categoryNo the value for tbl_nav_info.CATEGORY_NO
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    public void setCategoryNo(String categoryNo) {
        this.categoryNo = categoryNo == null ? null : categoryNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_nav_info.CATEGORY_NAME
     *
     * @return the value of tbl_nav_info.CATEGORY_NAME
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_nav_info.CATEGORY_NAME
     *
     * @param categoryName the value for tbl_nav_info.CATEGORY_NAME
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName == null ? null : categoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_nav_info.WEIBO_URL
     *
     * @return the value of tbl_nav_info.WEIBO_URL
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    public String getWeiboUrl() {
        return weiboUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_nav_info.WEIBO_URL
     *
     * @param weiboUrl the value for tbl_nav_info.WEIBO_URL
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    public void setWeiboUrl(String weiboUrl) {
        this.weiboUrl = weiboUrl == null ? null : weiboUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_nav_info.PROVINCE
     *
     * @return the value of tbl_nav_info.PROVINCE
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_nav_info.PROVINCE
     *
     * @param province the value for tbl_nav_info.PROVINCE
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_nav_info.CITY
     *
     * @return the value of tbl_nav_info.CITY
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_nav_info.CITY
     *
     * @param city the value for tbl_nav_info.CITY
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_nav_info.WEIXIN_ACCOUNT
     *
     * @return the value of tbl_nav_info.WEIXIN_ACCOUNT
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    public String getWeixinAccount() {
        return weixinAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_nav_info.WEIXIN_ACCOUNT
     *
     * @param weixinAccount the value for tbl_nav_info.WEIXIN_ACCOUNT
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    public void setWeixinAccount(String weixinAccount) {
        this.weixinAccount = weixinAccount == null ? null : weixinAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_nav_info.WEIXIN_NAME
     *
     * @return the value of tbl_nav_info.WEIXIN_NAME
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    public String getWeixinName() {
        return weixinName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_nav_info.WEIXIN_NAME
     *
     * @param weixinName the value for tbl_nav_info.WEIXIN_NAME
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    public void setWeixinName(String weixinName) {
        this.weixinName = weixinName == null ? null : weixinName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_nav_info.ICON_URL
     *
     * @return the value of tbl_nav_info.ICON_URL
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    public String getIconUrl() {
        return iconUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_nav_info.ICON_URL
     *
     * @param iconUrl the value for tbl_nav_info.ICON_URL
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    public void setIconUrl(String iconUrl) {
        this.iconUrl = iconUrl == null ? null : iconUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_nav_info.YX_EWM_URL
     *
     * @return the value of tbl_nav_info.YX_EWM_URL
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    public String getYxEwmUrl() {
        return yxEwmUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_nav_info.YX_EWM_URL
     *
     * @param yxEwmUrl the value for tbl_nav_info.YX_EWM_URL
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    public void setYxEwmUrl(String yxEwmUrl) {
        this.yxEwmUrl = yxEwmUrl == null ? null : yxEwmUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_nav_info.WX_EWM_URL
     *
     * @return the value of tbl_nav_info.WX_EWM_URL
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    public String getWxEwmUrl() {
        return wxEwmUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_nav_info.WX_EWM_URL
     *
     * @param wxEwmUrl the value for tbl_nav_info.WX_EWM_URL
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    public void setWxEwmUrl(String wxEwmUrl) {
        this.wxEwmUrl = wxEwmUrl == null ? null : wxEwmUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_nav_info.YIXIN_ACCOUNT
     *
     * @return the value of tbl_nav_info.YIXIN_ACCOUNT
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    public String getYixinAccount() {
        return yixinAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_nav_info.YIXIN_ACCOUNT
     *
     * @param yixinAccount the value for tbl_nav_info.YIXIN_ACCOUNT
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    public void setYixinAccount(String yixinAccount) {
        this.yixinAccount = yixinAccount == null ? null : yixinAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_nav_info.YIXIN_NAME
     *
     * @return the value of tbl_nav_info.YIXIN_NAME
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    public String getYixinName() {
        return yixinName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_nav_info.YIXIN_NAME
     *
     * @param yixinName the value for tbl_nav_info.YIXIN_NAME
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    public void setYixinName(String yixinName) {
        this.yixinName = yixinName == null ? null : yixinName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_nav_info.CREATE_DATE
     *
     * @return the value of tbl_nav_info.CREATE_DATE
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_nav_info.CREATE_DATE
     *
     * @param createDate the value for tbl_nav_info.CREATE_DATE
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_nav_info.UPDATE_DATE
     *
     * @return the value of tbl_nav_info.UPDATE_DATE
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_nav_info.UPDATE_DATE
     *
     * @param updateDate the value for tbl_nav_info.UPDATE_DATE
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_nav_info.PRIORITY
     *
     * @return the value of tbl_nav_info.PRIORITY
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_nav_info.PRIORITY
     *
     * @param priority the value for tbl_nav_info.PRIORITY
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_nav_info.USERNAME
     *
     * @return the value of tbl_nav_info.USERNAME
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_nav_info.USERNAME
     *
     * @param username the value for tbl_nav_info.USERNAME
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_nav_info.STATUS
     *
     * @return the value of tbl_nav_info.STATUS
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_nav_info.STATUS
     *
     * @param status the value for tbl_nav_info.STATUS
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_nav_info.CLICK_SUM
     *
     * @return the value of tbl_nav_info.CLICK_SUM
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    public Integer getClickSum() {
        return clickSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_nav_info.CLICK_SUM
     *
     * @param clickSum the value for tbl_nav_info.CLICK_SUM
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    public void setClickSum(Integer clickSum) {
        this.clickSum = clickSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_nav_info.REMARK
     *
     * @return the value of tbl_nav_info.REMARK
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_nav_info.REMARK
     *
     * @param remark the value for tbl_nav_info.REMARK
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}