package com.ezok.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class NavInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_nav_info
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_nav_info
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_nav_info
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_nav_info
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    public NavInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_nav_info
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_nav_info
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_nav_info
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_nav_info
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_nav_info
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_nav_info
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_nav_info
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_nav_info
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_nav_info
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_nav_info
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_nav_info
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNoIsNull() {
            addCriterion("NO is null");
            return (Criteria) this;
        }

        public Criteria andNoIsNotNull() {
            addCriterion("NO is not null");
            return (Criteria) this;
        }

        public Criteria andNoEqualTo(String value) {
            addCriterion("NO =", value, "no");
            return (Criteria) this;
        }

        public Criteria andNoNotEqualTo(String value) {
            addCriterion("NO <>", value, "no");
            return (Criteria) this;
        }

        public Criteria andNoGreaterThan(String value) {
            addCriterion("NO >", value, "no");
            return (Criteria) this;
        }

        public Criteria andNoGreaterThanOrEqualTo(String value) {
            addCriterion("NO >=", value, "no");
            return (Criteria) this;
        }

        public Criteria andNoLessThan(String value) {
            addCriterion("NO <", value, "no");
            return (Criteria) this;
        }

        public Criteria andNoLessThanOrEqualTo(String value) {
            addCriterion("NO <=", value, "no");
            return (Criteria) this;
        }

        public Criteria andNoLike(String value) {
            addCriterion("NO like", value, "no");
            return (Criteria) this;
        }

        public Criteria andNoNotLike(String value) {
            addCriterion("NO not like", value, "no");
            return (Criteria) this;
        }

        public Criteria andNoIn(List<String> values) {
            addCriterion("NO in", values, "no");
            return (Criteria) this;
        }

        public Criteria andNoNotIn(List<String> values) {
            addCriterion("NO not in", values, "no");
            return (Criteria) this;
        }

        public Criteria andNoBetween(String value1, String value2) {
            addCriterion("NO between", value1, value2, "no");
            return (Criteria) this;
        }

        public Criteria andNoNotBetween(String value1, String value2) {
            addCriterion("NO not between", value1, value2, "no");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("NAME is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("NAME is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("NAME =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("NAME <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("NAME >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("NAME >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("NAME <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("NAME <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("NAME like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("NAME not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("NAME in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("NAME not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("NAME between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("NAME not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andUrlIsNull() {
            addCriterion("URL is null");
            return (Criteria) this;
        }

        public Criteria andUrlIsNotNull() {
            addCriterion("URL is not null");
            return (Criteria) this;
        }

        public Criteria andUrlEqualTo(String value) {
            addCriterion("URL =", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotEqualTo(String value) {
            addCriterion("URL <>", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThan(String value) {
            addCriterion("URL >", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThanOrEqualTo(String value) {
            addCriterion("URL >=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThan(String value) {
            addCriterion("URL <", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThanOrEqualTo(String value) {
            addCriterion("URL <=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLike(String value) {
            addCriterion("URL like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotLike(String value) {
            addCriterion("URL not like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlIn(List<String> values) {
            addCriterion("URL in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotIn(List<String> values) {
            addCriterion("URL not in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlBetween(String value1, String value2) {
            addCriterion("URL between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotBetween(String value1, String value2) {
            addCriterion("URL not between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andSummaryIsNull() {
            addCriterion("SUMMARY is null");
            return (Criteria) this;
        }

        public Criteria andSummaryIsNotNull() {
            addCriterion("SUMMARY is not null");
            return (Criteria) this;
        }

        public Criteria andSummaryEqualTo(String value) {
            addCriterion("SUMMARY =", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryNotEqualTo(String value) {
            addCriterion("SUMMARY <>", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryGreaterThan(String value) {
            addCriterion("SUMMARY >", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryGreaterThanOrEqualTo(String value) {
            addCriterion("SUMMARY >=", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryLessThan(String value) {
            addCriterion("SUMMARY <", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryLessThanOrEqualTo(String value) {
            addCriterion("SUMMARY <=", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryLike(String value) {
            addCriterion("SUMMARY like", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryNotLike(String value) {
            addCriterion("SUMMARY not like", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryIn(List<String> values) {
            addCriterion("SUMMARY in", values, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryNotIn(List<String> values) {
            addCriterion("SUMMARY not in", values, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryBetween(String value1, String value2) {
            addCriterion("SUMMARY between", value1, value2, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryNotBetween(String value1, String value2) {
            addCriterion("SUMMARY not between", value1, value2, "summary");
            return (Criteria) this;
        }

        public Criteria andNavDescIsNull() {
            addCriterion("NAV_DESC is null");
            return (Criteria) this;
        }

        public Criteria andNavDescIsNotNull() {
            addCriterion("NAV_DESC is not null");
            return (Criteria) this;
        }

        public Criteria andNavDescEqualTo(String value) {
            addCriterion("NAV_DESC =", value, "navDesc");
            return (Criteria) this;
        }

        public Criteria andNavDescNotEqualTo(String value) {
            addCriterion("NAV_DESC <>", value, "navDesc");
            return (Criteria) this;
        }

        public Criteria andNavDescGreaterThan(String value) {
            addCriterion("NAV_DESC >", value, "navDesc");
            return (Criteria) this;
        }

        public Criteria andNavDescGreaterThanOrEqualTo(String value) {
            addCriterion("NAV_DESC >=", value, "navDesc");
            return (Criteria) this;
        }

        public Criteria andNavDescLessThan(String value) {
            addCriterion("NAV_DESC <", value, "navDesc");
            return (Criteria) this;
        }

        public Criteria andNavDescLessThanOrEqualTo(String value) {
            addCriterion("NAV_DESC <=", value, "navDesc");
            return (Criteria) this;
        }

        public Criteria andNavDescLike(String value) {
            addCriterion("NAV_DESC like", value, "navDesc");
            return (Criteria) this;
        }

        public Criteria andNavDescNotLike(String value) {
            addCriterion("NAV_DESC not like", value, "navDesc");
            return (Criteria) this;
        }

        public Criteria andNavDescIn(List<String> values) {
            addCriterion("NAV_DESC in", values, "navDesc");
            return (Criteria) this;
        }

        public Criteria andNavDescNotIn(List<String> values) {
            addCriterion("NAV_DESC not in", values, "navDesc");
            return (Criteria) this;
        }

        public Criteria andNavDescBetween(String value1, String value2) {
            addCriterion("NAV_DESC between", value1, value2, "navDesc");
            return (Criteria) this;
        }

        public Criteria andNavDescNotBetween(String value1, String value2) {
            addCriterion("NAV_DESC not between", value1, value2, "navDesc");
            return (Criteria) this;
        }

        public Criteria andCategoryNoIsNull() {
            addCriterion("CATEGORY_NO is null");
            return (Criteria) this;
        }

        public Criteria andCategoryNoIsNotNull() {
            addCriterion("CATEGORY_NO is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryNoEqualTo(String value) {
            addCriterion("CATEGORY_NO =", value, "categoryNo");
            return (Criteria) this;
        }

        public Criteria andCategoryNoNotEqualTo(String value) {
            addCriterion("CATEGORY_NO <>", value, "categoryNo");
            return (Criteria) this;
        }

        public Criteria andCategoryNoGreaterThan(String value) {
            addCriterion("CATEGORY_NO >", value, "categoryNo");
            return (Criteria) this;
        }

        public Criteria andCategoryNoGreaterThanOrEqualTo(String value) {
            addCriterion("CATEGORY_NO >=", value, "categoryNo");
            return (Criteria) this;
        }

        public Criteria andCategoryNoLessThan(String value) {
            addCriterion("CATEGORY_NO <", value, "categoryNo");
            return (Criteria) this;
        }

        public Criteria andCategoryNoLessThanOrEqualTo(String value) {
            addCriterion("CATEGORY_NO <=", value, "categoryNo");
            return (Criteria) this;
        }

        public Criteria andCategoryNoLike(String value) {
            addCriterion("CATEGORY_NO like", value, "categoryNo");
            return (Criteria) this;
        }

        public Criteria andCategoryNoNotLike(String value) {
            addCriterion("CATEGORY_NO not like", value, "categoryNo");
            return (Criteria) this;
        }

        public Criteria andCategoryNoIn(List<String> values) {
            addCriterion("CATEGORY_NO in", values, "categoryNo");
            return (Criteria) this;
        }

        public Criteria andCategoryNoNotIn(List<String> values) {
            addCriterion("CATEGORY_NO not in", values, "categoryNo");
            return (Criteria) this;
        }

        public Criteria andCategoryNoBetween(String value1, String value2) {
            addCriterion("CATEGORY_NO between", value1, value2, "categoryNo");
            return (Criteria) this;
        }

        public Criteria andCategoryNoNotBetween(String value1, String value2) {
            addCriterion("CATEGORY_NO not between", value1, value2, "categoryNo");
            return (Criteria) this;
        }

        public Criteria andCategoryNameIsNull() {
            addCriterion("CATEGORY_NAME is null");
            return (Criteria) this;
        }

        public Criteria andCategoryNameIsNotNull() {
            addCriterion("CATEGORY_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryNameEqualTo(String value) {
            addCriterion("CATEGORY_NAME =", value, "categoryName");
            return (Criteria) this;
        }

        public Criteria andCategoryNameNotEqualTo(String value) {
            addCriterion("CATEGORY_NAME <>", value, "categoryName");
            return (Criteria) this;
        }

        public Criteria andCategoryNameGreaterThan(String value) {
            addCriterion("CATEGORY_NAME >", value, "categoryName");
            return (Criteria) this;
        }

        public Criteria andCategoryNameGreaterThanOrEqualTo(String value) {
            addCriterion("CATEGORY_NAME >=", value, "categoryName");
            return (Criteria) this;
        }

        public Criteria andCategoryNameLessThan(String value) {
            addCriterion("CATEGORY_NAME <", value, "categoryName");
            return (Criteria) this;
        }

        public Criteria andCategoryNameLessThanOrEqualTo(String value) {
            addCriterion("CATEGORY_NAME <=", value, "categoryName");
            return (Criteria) this;
        }

        public Criteria andCategoryNameLike(String value) {
            addCriterion("CATEGORY_NAME like", value, "categoryName");
            return (Criteria) this;
        }

        public Criteria andCategoryNameNotLike(String value) {
            addCriterion("CATEGORY_NAME not like", value, "categoryName");
            return (Criteria) this;
        }

        public Criteria andCategoryNameIn(List<String> values) {
            addCriterion("CATEGORY_NAME in", values, "categoryName");
            return (Criteria) this;
        }

        public Criteria andCategoryNameNotIn(List<String> values) {
            addCriterion("CATEGORY_NAME not in", values, "categoryName");
            return (Criteria) this;
        }

        public Criteria andCategoryNameBetween(String value1, String value2) {
            addCriterion("CATEGORY_NAME between", value1, value2, "categoryName");
            return (Criteria) this;
        }

        public Criteria andCategoryNameNotBetween(String value1, String value2) {
            addCriterion("CATEGORY_NAME not between", value1, value2, "categoryName");
            return (Criteria) this;
        }

        public Criteria andWeiboUrlIsNull() {
            addCriterion("WEIBO_URL is null");
            return (Criteria) this;
        }

        public Criteria andWeiboUrlIsNotNull() {
            addCriterion("WEIBO_URL is not null");
            return (Criteria) this;
        }

        public Criteria andWeiboUrlEqualTo(String value) {
            addCriterion("WEIBO_URL =", value, "weiboUrl");
            return (Criteria) this;
        }

        public Criteria andWeiboUrlNotEqualTo(String value) {
            addCriterion("WEIBO_URL <>", value, "weiboUrl");
            return (Criteria) this;
        }

        public Criteria andWeiboUrlGreaterThan(String value) {
            addCriterion("WEIBO_URL >", value, "weiboUrl");
            return (Criteria) this;
        }

        public Criteria andWeiboUrlGreaterThanOrEqualTo(String value) {
            addCriterion("WEIBO_URL >=", value, "weiboUrl");
            return (Criteria) this;
        }

        public Criteria andWeiboUrlLessThan(String value) {
            addCriterion("WEIBO_URL <", value, "weiboUrl");
            return (Criteria) this;
        }

        public Criteria andWeiboUrlLessThanOrEqualTo(String value) {
            addCriterion("WEIBO_URL <=", value, "weiboUrl");
            return (Criteria) this;
        }

        public Criteria andWeiboUrlLike(String value) {
            addCriterion("WEIBO_URL like", value, "weiboUrl");
            return (Criteria) this;
        }

        public Criteria andWeiboUrlNotLike(String value) {
            addCriterion("WEIBO_URL not like", value, "weiboUrl");
            return (Criteria) this;
        }

        public Criteria andWeiboUrlIn(List<String> values) {
            addCriterion("WEIBO_URL in", values, "weiboUrl");
            return (Criteria) this;
        }

        public Criteria andWeiboUrlNotIn(List<String> values) {
            addCriterion("WEIBO_URL not in", values, "weiboUrl");
            return (Criteria) this;
        }

        public Criteria andWeiboUrlBetween(String value1, String value2) {
            addCriterion("WEIBO_URL between", value1, value2, "weiboUrl");
            return (Criteria) this;
        }

        public Criteria andWeiboUrlNotBetween(String value1, String value2) {
            addCriterion("WEIBO_URL not between", value1, value2, "weiboUrl");
            return (Criteria) this;
        }

        public Criteria andProvinceIsNull() {
            addCriterion("PROVINCE is null");
            return (Criteria) this;
        }

        public Criteria andProvinceIsNotNull() {
            addCriterion("PROVINCE is not null");
            return (Criteria) this;
        }

        public Criteria andProvinceEqualTo(String value) {
            addCriterion("PROVINCE =", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotEqualTo(String value) {
            addCriterion("PROVINCE <>", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceGreaterThan(String value) {
            addCriterion("PROVINCE >", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceGreaterThanOrEqualTo(String value) {
            addCriterion("PROVINCE >=", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLessThan(String value) {
            addCriterion("PROVINCE <", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLessThanOrEqualTo(String value) {
            addCriterion("PROVINCE <=", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLike(String value) {
            addCriterion("PROVINCE like", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotLike(String value) {
            addCriterion("PROVINCE not like", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceIn(List<String> values) {
            addCriterion("PROVINCE in", values, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotIn(List<String> values) {
            addCriterion("PROVINCE not in", values, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceBetween(String value1, String value2) {
            addCriterion("PROVINCE between", value1, value2, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotBetween(String value1, String value2) {
            addCriterion("PROVINCE not between", value1, value2, "province");
            return (Criteria) this;
        }

        public Criteria andCityIsNull() {
            addCriterion("CITY is null");
            return (Criteria) this;
        }

        public Criteria andCityIsNotNull() {
            addCriterion("CITY is not null");
            return (Criteria) this;
        }

        public Criteria andCityEqualTo(String value) {
            addCriterion("CITY =", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotEqualTo(String value) {
            addCriterion("CITY <>", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThan(String value) {
            addCriterion("CITY >", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThanOrEqualTo(String value) {
            addCriterion("CITY >=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThan(String value) {
            addCriterion("CITY <", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThanOrEqualTo(String value) {
            addCriterion("CITY <=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLike(String value) {
            addCriterion("CITY like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotLike(String value) {
            addCriterion("CITY not like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityIn(List<String> values) {
            addCriterion("CITY in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotIn(List<String> values) {
            addCriterion("CITY not in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityBetween(String value1, String value2) {
            addCriterion("CITY between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotBetween(String value1, String value2) {
            addCriterion("CITY not between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andWeixinAccountIsNull() {
            addCriterion("WEIXIN_ACCOUNT is null");
            return (Criteria) this;
        }

        public Criteria andWeixinAccountIsNotNull() {
            addCriterion("WEIXIN_ACCOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andWeixinAccountEqualTo(String value) {
            addCriterion("WEIXIN_ACCOUNT =", value, "weixinAccount");
            return (Criteria) this;
        }

        public Criteria andWeixinAccountNotEqualTo(String value) {
            addCriterion("WEIXIN_ACCOUNT <>", value, "weixinAccount");
            return (Criteria) this;
        }

        public Criteria andWeixinAccountGreaterThan(String value) {
            addCriterion("WEIXIN_ACCOUNT >", value, "weixinAccount");
            return (Criteria) this;
        }

        public Criteria andWeixinAccountGreaterThanOrEqualTo(String value) {
            addCriterion("WEIXIN_ACCOUNT >=", value, "weixinAccount");
            return (Criteria) this;
        }

        public Criteria andWeixinAccountLessThan(String value) {
            addCriterion("WEIXIN_ACCOUNT <", value, "weixinAccount");
            return (Criteria) this;
        }

        public Criteria andWeixinAccountLessThanOrEqualTo(String value) {
            addCriterion("WEIXIN_ACCOUNT <=", value, "weixinAccount");
            return (Criteria) this;
        }

        public Criteria andWeixinAccountLike(String value) {
            addCriterion("WEIXIN_ACCOUNT like", value, "weixinAccount");
            return (Criteria) this;
        }

        public Criteria andWeixinAccountNotLike(String value) {
            addCriterion("WEIXIN_ACCOUNT not like", value, "weixinAccount");
            return (Criteria) this;
        }

        public Criteria andWeixinAccountIn(List<String> values) {
            addCriterion("WEIXIN_ACCOUNT in", values, "weixinAccount");
            return (Criteria) this;
        }

        public Criteria andWeixinAccountNotIn(List<String> values) {
            addCriterion("WEIXIN_ACCOUNT not in", values, "weixinAccount");
            return (Criteria) this;
        }

        public Criteria andWeixinAccountBetween(String value1, String value2) {
            addCriterion("WEIXIN_ACCOUNT between", value1, value2, "weixinAccount");
            return (Criteria) this;
        }

        public Criteria andWeixinAccountNotBetween(String value1, String value2) {
            addCriterion("WEIXIN_ACCOUNT not between", value1, value2, "weixinAccount");
            return (Criteria) this;
        }

        public Criteria andWeixinNameIsNull() {
            addCriterion("WEIXIN_NAME is null");
            return (Criteria) this;
        }

        public Criteria andWeixinNameIsNotNull() {
            addCriterion("WEIXIN_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andWeixinNameEqualTo(String value) {
            addCriterion("WEIXIN_NAME =", value, "weixinName");
            return (Criteria) this;
        }

        public Criteria andWeixinNameNotEqualTo(String value) {
            addCriterion("WEIXIN_NAME <>", value, "weixinName");
            return (Criteria) this;
        }

        public Criteria andWeixinNameGreaterThan(String value) {
            addCriterion("WEIXIN_NAME >", value, "weixinName");
            return (Criteria) this;
        }

        public Criteria andWeixinNameGreaterThanOrEqualTo(String value) {
            addCriterion("WEIXIN_NAME >=", value, "weixinName");
            return (Criteria) this;
        }

        public Criteria andWeixinNameLessThan(String value) {
            addCriterion("WEIXIN_NAME <", value, "weixinName");
            return (Criteria) this;
        }

        public Criteria andWeixinNameLessThanOrEqualTo(String value) {
            addCriterion("WEIXIN_NAME <=", value, "weixinName");
            return (Criteria) this;
        }

        public Criteria andWeixinNameLike(String value) {
            addCriterion("WEIXIN_NAME like", value, "weixinName");
            return (Criteria) this;
        }

        public Criteria andWeixinNameNotLike(String value) {
            addCriterion("WEIXIN_NAME not like", value, "weixinName");
            return (Criteria) this;
        }

        public Criteria andWeixinNameIn(List<String> values) {
            addCriterion("WEIXIN_NAME in", values, "weixinName");
            return (Criteria) this;
        }

        public Criteria andWeixinNameNotIn(List<String> values) {
            addCriterion("WEIXIN_NAME not in", values, "weixinName");
            return (Criteria) this;
        }

        public Criteria andWeixinNameBetween(String value1, String value2) {
            addCriterion("WEIXIN_NAME between", value1, value2, "weixinName");
            return (Criteria) this;
        }

        public Criteria andWeixinNameNotBetween(String value1, String value2) {
            addCriterion("WEIXIN_NAME not between", value1, value2, "weixinName");
            return (Criteria) this;
        }

        public Criteria andIconUrlIsNull() {
            addCriterion("ICON_URL is null");
            return (Criteria) this;
        }

        public Criteria andIconUrlIsNotNull() {
            addCriterion("ICON_URL is not null");
            return (Criteria) this;
        }

        public Criteria andIconUrlEqualTo(String value) {
            addCriterion("ICON_URL =", value, "iconUrl");
            return (Criteria) this;
        }

        public Criteria andIconUrlNotEqualTo(String value) {
            addCriterion("ICON_URL <>", value, "iconUrl");
            return (Criteria) this;
        }

        public Criteria andIconUrlGreaterThan(String value) {
            addCriterion("ICON_URL >", value, "iconUrl");
            return (Criteria) this;
        }

        public Criteria andIconUrlGreaterThanOrEqualTo(String value) {
            addCriterion("ICON_URL >=", value, "iconUrl");
            return (Criteria) this;
        }

        public Criteria andIconUrlLessThan(String value) {
            addCriterion("ICON_URL <", value, "iconUrl");
            return (Criteria) this;
        }

        public Criteria andIconUrlLessThanOrEqualTo(String value) {
            addCriterion("ICON_URL <=", value, "iconUrl");
            return (Criteria) this;
        }

        public Criteria andIconUrlLike(String value) {
            addCriterion("ICON_URL like", value, "iconUrl");
            return (Criteria) this;
        }

        public Criteria andIconUrlNotLike(String value) {
            addCriterion("ICON_URL not like", value, "iconUrl");
            return (Criteria) this;
        }

        public Criteria andIconUrlIn(List<String> values) {
            addCriterion("ICON_URL in", values, "iconUrl");
            return (Criteria) this;
        }

        public Criteria andIconUrlNotIn(List<String> values) {
            addCriterion("ICON_URL not in", values, "iconUrl");
            return (Criteria) this;
        }

        public Criteria andIconUrlBetween(String value1, String value2) {
            addCriterion("ICON_URL between", value1, value2, "iconUrl");
            return (Criteria) this;
        }

        public Criteria andIconUrlNotBetween(String value1, String value2) {
            addCriterion("ICON_URL not between", value1, value2, "iconUrl");
            return (Criteria) this;
        }

        public Criteria andYxEwmUrlIsNull() {
            addCriterion("YX_EWM_URL is null");
            return (Criteria) this;
        }

        public Criteria andYxEwmUrlIsNotNull() {
            addCriterion("YX_EWM_URL is not null");
            return (Criteria) this;
        }

        public Criteria andYxEwmUrlEqualTo(String value) {
            addCriterion("YX_EWM_URL =", value, "yxEwmUrl");
            return (Criteria) this;
        }

        public Criteria andYxEwmUrlNotEqualTo(String value) {
            addCriterion("YX_EWM_URL <>", value, "yxEwmUrl");
            return (Criteria) this;
        }

        public Criteria andYxEwmUrlGreaterThan(String value) {
            addCriterion("YX_EWM_URL >", value, "yxEwmUrl");
            return (Criteria) this;
        }

        public Criteria andYxEwmUrlGreaterThanOrEqualTo(String value) {
            addCriterion("YX_EWM_URL >=", value, "yxEwmUrl");
            return (Criteria) this;
        }

        public Criteria andYxEwmUrlLessThan(String value) {
            addCriterion("YX_EWM_URL <", value, "yxEwmUrl");
            return (Criteria) this;
        }

        public Criteria andYxEwmUrlLessThanOrEqualTo(String value) {
            addCriterion("YX_EWM_URL <=", value, "yxEwmUrl");
            return (Criteria) this;
        }

        public Criteria andYxEwmUrlLike(String value) {
            addCriterion("YX_EWM_URL like", value, "yxEwmUrl");
            return (Criteria) this;
        }

        public Criteria andYxEwmUrlNotLike(String value) {
            addCriterion("YX_EWM_URL not like", value, "yxEwmUrl");
            return (Criteria) this;
        }

        public Criteria andYxEwmUrlIn(List<String> values) {
            addCriterion("YX_EWM_URL in", values, "yxEwmUrl");
            return (Criteria) this;
        }

        public Criteria andYxEwmUrlNotIn(List<String> values) {
            addCriterion("YX_EWM_URL not in", values, "yxEwmUrl");
            return (Criteria) this;
        }

        public Criteria andYxEwmUrlBetween(String value1, String value2) {
            addCriterion("YX_EWM_URL between", value1, value2, "yxEwmUrl");
            return (Criteria) this;
        }

        public Criteria andYxEwmUrlNotBetween(String value1, String value2) {
            addCriterion("YX_EWM_URL not between", value1, value2, "yxEwmUrl");
            return (Criteria) this;
        }

        public Criteria andWxEwmUrlIsNull() {
            addCriterion("WX_EWM_URL is null");
            return (Criteria) this;
        }

        public Criteria andWxEwmUrlIsNotNull() {
            addCriterion("WX_EWM_URL is not null");
            return (Criteria) this;
        }

        public Criteria andWxEwmUrlEqualTo(String value) {
            addCriterion("WX_EWM_URL =", value, "wxEwmUrl");
            return (Criteria) this;
        }

        public Criteria andWxEwmUrlNotEqualTo(String value) {
            addCriterion("WX_EWM_URL <>", value, "wxEwmUrl");
            return (Criteria) this;
        }

        public Criteria andWxEwmUrlGreaterThan(String value) {
            addCriterion("WX_EWM_URL >", value, "wxEwmUrl");
            return (Criteria) this;
        }

        public Criteria andWxEwmUrlGreaterThanOrEqualTo(String value) {
            addCriterion("WX_EWM_URL >=", value, "wxEwmUrl");
            return (Criteria) this;
        }

        public Criteria andWxEwmUrlLessThan(String value) {
            addCriterion("WX_EWM_URL <", value, "wxEwmUrl");
            return (Criteria) this;
        }

        public Criteria andWxEwmUrlLessThanOrEqualTo(String value) {
            addCriterion("WX_EWM_URL <=", value, "wxEwmUrl");
            return (Criteria) this;
        }

        public Criteria andWxEwmUrlLike(String value) {
            addCriterion("WX_EWM_URL like", value, "wxEwmUrl");
            return (Criteria) this;
        }

        public Criteria andWxEwmUrlNotLike(String value) {
            addCriterion("WX_EWM_URL not like", value, "wxEwmUrl");
            return (Criteria) this;
        }

        public Criteria andWxEwmUrlIn(List<String> values) {
            addCriterion("WX_EWM_URL in", values, "wxEwmUrl");
            return (Criteria) this;
        }

        public Criteria andWxEwmUrlNotIn(List<String> values) {
            addCriterion("WX_EWM_URL not in", values, "wxEwmUrl");
            return (Criteria) this;
        }

        public Criteria andWxEwmUrlBetween(String value1, String value2) {
            addCriterion("WX_EWM_URL between", value1, value2, "wxEwmUrl");
            return (Criteria) this;
        }

        public Criteria andWxEwmUrlNotBetween(String value1, String value2) {
            addCriterion("WX_EWM_URL not between", value1, value2, "wxEwmUrl");
            return (Criteria) this;
        }

        public Criteria andYixinAccountIsNull() {
            addCriterion("YIXIN_ACCOUNT is null");
            return (Criteria) this;
        }

        public Criteria andYixinAccountIsNotNull() {
            addCriterion("YIXIN_ACCOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andYixinAccountEqualTo(String value) {
            addCriterion("YIXIN_ACCOUNT =", value, "yixinAccount");
            return (Criteria) this;
        }

        public Criteria andYixinAccountNotEqualTo(String value) {
            addCriterion("YIXIN_ACCOUNT <>", value, "yixinAccount");
            return (Criteria) this;
        }

        public Criteria andYixinAccountGreaterThan(String value) {
            addCriterion("YIXIN_ACCOUNT >", value, "yixinAccount");
            return (Criteria) this;
        }

        public Criteria andYixinAccountGreaterThanOrEqualTo(String value) {
            addCriterion("YIXIN_ACCOUNT >=", value, "yixinAccount");
            return (Criteria) this;
        }

        public Criteria andYixinAccountLessThan(String value) {
            addCriterion("YIXIN_ACCOUNT <", value, "yixinAccount");
            return (Criteria) this;
        }

        public Criteria andYixinAccountLessThanOrEqualTo(String value) {
            addCriterion("YIXIN_ACCOUNT <=", value, "yixinAccount");
            return (Criteria) this;
        }

        public Criteria andYixinAccountLike(String value) {
            addCriterion("YIXIN_ACCOUNT like", value, "yixinAccount");
            return (Criteria) this;
        }

        public Criteria andYixinAccountNotLike(String value) {
            addCriterion("YIXIN_ACCOUNT not like", value, "yixinAccount");
            return (Criteria) this;
        }

        public Criteria andYixinAccountIn(List<String> values) {
            addCriterion("YIXIN_ACCOUNT in", values, "yixinAccount");
            return (Criteria) this;
        }

        public Criteria andYixinAccountNotIn(List<String> values) {
            addCriterion("YIXIN_ACCOUNT not in", values, "yixinAccount");
            return (Criteria) this;
        }

        public Criteria andYixinAccountBetween(String value1, String value2) {
            addCriterion("YIXIN_ACCOUNT between", value1, value2, "yixinAccount");
            return (Criteria) this;
        }

        public Criteria andYixinAccountNotBetween(String value1, String value2) {
            addCriterion("YIXIN_ACCOUNT not between", value1, value2, "yixinAccount");
            return (Criteria) this;
        }

        public Criteria andYixinNameIsNull() {
            addCriterion("YIXIN_NAME is null");
            return (Criteria) this;
        }

        public Criteria andYixinNameIsNotNull() {
            addCriterion("YIXIN_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andYixinNameEqualTo(String value) {
            addCriterion("YIXIN_NAME =", value, "yixinName");
            return (Criteria) this;
        }

        public Criteria andYixinNameNotEqualTo(String value) {
            addCriterion("YIXIN_NAME <>", value, "yixinName");
            return (Criteria) this;
        }

        public Criteria andYixinNameGreaterThan(String value) {
            addCriterion("YIXIN_NAME >", value, "yixinName");
            return (Criteria) this;
        }

        public Criteria andYixinNameGreaterThanOrEqualTo(String value) {
            addCriterion("YIXIN_NAME >=", value, "yixinName");
            return (Criteria) this;
        }

        public Criteria andYixinNameLessThan(String value) {
            addCriterion("YIXIN_NAME <", value, "yixinName");
            return (Criteria) this;
        }

        public Criteria andYixinNameLessThanOrEqualTo(String value) {
            addCriterion("YIXIN_NAME <=", value, "yixinName");
            return (Criteria) this;
        }

        public Criteria andYixinNameLike(String value) {
            addCriterion("YIXIN_NAME like", value, "yixinName");
            return (Criteria) this;
        }

        public Criteria andYixinNameNotLike(String value) {
            addCriterion("YIXIN_NAME not like", value, "yixinName");
            return (Criteria) this;
        }

        public Criteria andYixinNameIn(List<String> values) {
            addCriterion("YIXIN_NAME in", values, "yixinName");
            return (Criteria) this;
        }

        public Criteria andYixinNameNotIn(List<String> values) {
            addCriterion("YIXIN_NAME not in", values, "yixinName");
            return (Criteria) this;
        }

        public Criteria andYixinNameBetween(String value1, String value2) {
            addCriterion("YIXIN_NAME between", value1, value2, "yixinName");
            return (Criteria) this;
        }

        public Criteria andYixinNameNotBetween(String value1, String value2) {
            addCriterion("YIXIN_NAME not between", value1, value2, "yixinName");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("CREATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("CREATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("CREATE_DATE =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("CREATE_DATE <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("CREATE_DATE >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("CREATE_DATE <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("CREATE_DATE in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("CREATE_DATE not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("UPDATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("UPDATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("UPDATE_DATE =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("UPDATE_DATE <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("UPDATE_DATE >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_DATE >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("UPDATE_DATE <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_DATE <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("UPDATE_DATE in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("UPDATE_DATE not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("UPDATE_DATE between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_DATE not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andPriorityIsNull() {
            addCriterion("PRIORITY is null");
            return (Criteria) this;
        }

        public Criteria andPriorityIsNotNull() {
            addCriterion("PRIORITY is not null");
            return (Criteria) this;
        }

        public Criteria andPriorityEqualTo(Integer value) {
            addCriterion("PRIORITY =", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityNotEqualTo(Integer value) {
            addCriterion("PRIORITY <>", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityGreaterThan(Integer value) {
            addCriterion("PRIORITY >", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityGreaterThanOrEqualTo(Integer value) {
            addCriterion("PRIORITY >=", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityLessThan(Integer value) {
            addCriterion("PRIORITY <", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityLessThanOrEqualTo(Integer value) {
            addCriterion("PRIORITY <=", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityIn(List<Integer> values) {
            addCriterion("PRIORITY in", values, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityNotIn(List<Integer> values) {
            addCriterion("PRIORITY not in", values, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityBetween(Integer value1, Integer value2) {
            addCriterion("PRIORITY between", value1, value2, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityNotBetween(Integer value1, Integer value2) {
            addCriterion("PRIORITY not between", value1, value2, "priority");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNull() {
            addCriterion("USERNAME is null");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNotNull() {
            addCriterion("USERNAME is not null");
            return (Criteria) this;
        }

        public Criteria andUsernameEqualTo(String value) {
            addCriterion("USERNAME =", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotEqualTo(String value) {
            addCriterion("USERNAME <>", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThan(String value) {
            addCriterion("USERNAME >", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("USERNAME >=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThan(String value) {
            addCriterion("USERNAME <", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThanOrEqualTo(String value) {
            addCriterion("USERNAME <=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLike(String value) {
            addCriterion("USERNAME like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotLike(String value) {
            addCriterion("USERNAME not like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameIn(List<String> values) {
            addCriterion("USERNAME in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotIn(List<String> values) {
            addCriterion("USERNAME not in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameBetween(String value1, String value2) {
            addCriterion("USERNAME between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotBetween(String value1, String value2) {
            addCriterion("USERNAME not between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andClickSumIsNull() {
            addCriterion("CLICK_SUM is null");
            return (Criteria) this;
        }

        public Criteria andClickSumIsNotNull() {
            addCriterion("CLICK_SUM is not null");
            return (Criteria) this;
        }

        public Criteria andClickSumEqualTo(Integer value) {
            addCriterion("CLICK_SUM =", value, "clickSum");
            return (Criteria) this;
        }

        public Criteria andClickSumNotEqualTo(Integer value) {
            addCriterion("CLICK_SUM <>", value, "clickSum");
            return (Criteria) this;
        }

        public Criteria andClickSumGreaterThan(Integer value) {
            addCriterion("CLICK_SUM >", value, "clickSum");
            return (Criteria) this;
        }

        public Criteria andClickSumGreaterThanOrEqualTo(Integer value) {
            addCriterion("CLICK_SUM >=", value, "clickSum");
            return (Criteria) this;
        }

        public Criteria andClickSumLessThan(Integer value) {
            addCriterion("CLICK_SUM <", value, "clickSum");
            return (Criteria) this;
        }

        public Criteria andClickSumLessThanOrEqualTo(Integer value) {
            addCriterion("CLICK_SUM <=", value, "clickSum");
            return (Criteria) this;
        }

        public Criteria andClickSumIn(List<Integer> values) {
            addCriterion("CLICK_SUM in", values, "clickSum");
            return (Criteria) this;
        }

        public Criteria andClickSumNotIn(List<Integer> values) {
            addCriterion("CLICK_SUM not in", values, "clickSum");
            return (Criteria) this;
        }

        public Criteria andClickSumBetween(Integer value1, Integer value2) {
            addCriterion("CLICK_SUM between", value1, value2, "clickSum");
            return (Criteria) this;
        }

        public Criteria andClickSumNotBetween(Integer value1, Integer value2) {
            addCriterion("CLICK_SUM not between", value1, value2, "clickSum");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_nav_info
     *
     * @mbggenerated do_not_delete_during_merge Tue Apr 01 11:41:48 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_nav_info
     *
     * @mbggenerated Tue Apr 01 11:41:48 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}