package com.ezok.model;

import java.util.Date;

public class NavRelArticle {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_rel_nav_article.ID
     *
     * @mbggenerated Thu Apr 17 22:57:42 CST 2014
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_rel_nav_article.NAV_INFO_ID
     *
     * @mbggenerated Thu Apr 17 22:57:42 CST 2014
     */
    private String navInfoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_rel_nav_article.WEIXIN_ACCOUNT
     *
     * @mbggenerated Thu Apr 17 22:57:42 CST 2014
     */
    private String weixinAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_rel_nav_article.WEIXIN_NAME
     *
     * @mbggenerated Thu Apr 17 22:57:42 CST 2014
     */
    private String weixinName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_rel_nav_article.BIZ_ID
     *
     * @mbggenerated Thu Apr 17 22:57:42 CST 2014
     */
    private String bizId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_rel_nav_article.IS_GRAB
     *
     * @mbggenerated Thu Apr 17 22:57:42 CST 2014
     */
    private String isGrab;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_rel_nav_article.CREATE_DATE
     *
     * @mbggenerated Thu Apr 17 22:57:42 CST 2014
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_rel_nav_article.UPDATE_DATE
     *
     * @mbggenerated Thu Apr 17 22:57:42 CST 2014
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_rel_nav_article.ID
     *
     * @return the value of tbl_rel_nav_article.ID
     *
     * @mbggenerated Thu Apr 17 22:57:42 CST 2014
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_rel_nav_article.ID
     *
     * @param id the value for tbl_rel_nav_article.ID
     *
     * @mbggenerated Thu Apr 17 22:57:42 CST 2014
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_rel_nav_article.NAV_INFO_ID
     *
     * @return the value of tbl_rel_nav_article.NAV_INFO_ID
     *
     * @mbggenerated Thu Apr 17 22:57:42 CST 2014
     */
    public String getNavInfoId() {
        return navInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_rel_nav_article.NAV_INFO_ID
     *
     * @param navInfoId the value for tbl_rel_nav_article.NAV_INFO_ID
     *
     * @mbggenerated Thu Apr 17 22:57:42 CST 2014
     */
    public void setNavInfoId(String navInfoId) {
        this.navInfoId = navInfoId == null ? null : navInfoId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_rel_nav_article.WEIXIN_ACCOUNT
     *
     * @return the value of tbl_rel_nav_article.WEIXIN_ACCOUNT
     *
     * @mbggenerated Thu Apr 17 22:57:42 CST 2014
     */
    public String getWeixinAccount() {
        return weixinAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_rel_nav_article.WEIXIN_ACCOUNT
     *
     * @param weixinAccount the value for tbl_rel_nav_article.WEIXIN_ACCOUNT
     *
     * @mbggenerated Thu Apr 17 22:57:42 CST 2014
     */
    public void setWeixinAccount(String weixinAccount) {
        this.weixinAccount = weixinAccount == null ? null : weixinAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_rel_nav_article.WEIXIN_NAME
     *
     * @return the value of tbl_rel_nav_article.WEIXIN_NAME
     *
     * @mbggenerated Thu Apr 17 22:57:42 CST 2014
     */
    public String getWeixinName() {
        return weixinName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_rel_nav_article.WEIXIN_NAME
     *
     * @param weixinName the value for tbl_rel_nav_article.WEIXIN_NAME
     *
     * @mbggenerated Thu Apr 17 22:57:42 CST 2014
     */
    public void setWeixinName(String weixinName) {
        this.weixinName = weixinName == null ? null : weixinName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_rel_nav_article.BIZ_ID
     *
     * @return the value of tbl_rel_nav_article.BIZ_ID
     *
     * @mbggenerated Thu Apr 17 22:57:42 CST 2014
     */
    public String getBizId() {
        return bizId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_rel_nav_article.BIZ_ID
     *
     * @param bizId the value for tbl_rel_nav_article.BIZ_ID
     *
     * @mbggenerated Thu Apr 17 22:57:42 CST 2014
     */
    public void setBizId(String bizId) {
        this.bizId = bizId == null ? null : bizId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_rel_nav_article.IS_GRAB
     *
     * @return the value of tbl_rel_nav_article.IS_GRAB
     *
     * @mbggenerated Thu Apr 17 22:57:42 CST 2014
     */
    public String getIsGrab() {
        return isGrab;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_rel_nav_article.IS_GRAB
     *
     * @param isGrab the value for tbl_rel_nav_article.IS_GRAB
     *
     * @mbggenerated Thu Apr 17 22:57:42 CST 2014
     */
    public void setIsGrab(String isGrab) {
        this.isGrab = isGrab == null ? null : isGrab.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_rel_nav_article.CREATE_DATE
     *
     * @return the value of tbl_rel_nav_article.CREATE_DATE
     *
     * @mbggenerated Thu Apr 17 22:57:42 CST 2014
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_rel_nav_article.CREATE_DATE
     *
     * @param createDate the value for tbl_rel_nav_article.CREATE_DATE
     *
     * @mbggenerated Thu Apr 17 22:57:42 CST 2014
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_rel_nav_article.UPDATE_DATE
     *
     * @return the value of tbl_rel_nav_article.UPDATE_DATE
     *
     * @mbggenerated Thu Apr 17 22:57:42 CST 2014
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_rel_nav_article.UPDATE_DATE
     *
     * @param updateDate the value for tbl_rel_nav_article.UPDATE_DATE
     *
     * @mbggenerated Thu Apr 17 22:57:42 CST 2014
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}