package com.ezok.model;

import java.util.Date;

public class NavWeek {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_nav_week.ID
     *
     * @mbggenerated Wed Mar 26 13:14:41 CST 2014
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_nav_week.NAV_NO
     *
     * @mbggenerated Wed Mar 26 13:14:41 CST 2014
     */
    private String navNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_nav_week.TOP_REASON
     *
     * @mbggenerated Wed Mar 26 13:14:41 CST 2014
     */
    private String topReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_nav_week.UPDATE_DATE
     *
     * @mbggenerated Wed Mar 26 13:14:41 CST 2014
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_nav_week.ID
     *
     * @return the value of tbl_nav_week.ID
     *
     * @mbggenerated Wed Mar 26 13:14:41 CST 2014
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_nav_week.ID
     *
     * @param id the value for tbl_nav_week.ID
     *
     * @mbggenerated Wed Mar 26 13:14:41 CST 2014
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_nav_week.NAV_NO
     *
     * @return the value of tbl_nav_week.NAV_NO
     *
     * @mbggenerated Wed Mar 26 13:14:41 CST 2014
     */
    public String getNavNo() {
        return navNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_nav_week.NAV_NO
     *
     * @param navNo the value for tbl_nav_week.NAV_NO
     *
     * @mbggenerated Wed Mar 26 13:14:41 CST 2014
     */
    public void setNavNo(String navNo) {
        this.navNo = navNo == null ? null : navNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_nav_week.TOP_REASON
     *
     * @return the value of tbl_nav_week.TOP_REASON
     *
     * @mbggenerated Wed Mar 26 13:14:41 CST 2014
     */
    public String getTopReason() {
        return topReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_nav_week.TOP_REASON
     *
     * @param topReason the value for tbl_nav_week.TOP_REASON
     *
     * @mbggenerated Wed Mar 26 13:14:41 CST 2014
     */
    public void setTopReason(String topReason) {
        this.topReason = topReason == null ? null : topReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_nav_week.UPDATE_DATE
     *
     * @return the value of tbl_nav_week.UPDATE_DATE
     *
     * @mbggenerated Wed Mar 26 13:14:41 CST 2014
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_nav_week.UPDATE_DATE
     *
     * @param updateDate the value for tbl_nav_week.UPDATE_DATE
     *
     * @mbggenerated Wed Mar 26 13:14:41 CST 2014
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}