package com.ezok.model;

import java.util.Date;

public class UserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user_info.ID
     *
     * @mbggenerated Mon Feb 24 23:21:02 CST 2014
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user_info.USERNAME
     *
     * @mbggenerated Mon Feb 24 23:21:02 CST 2014
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user_info.PASSWORD
     *
     * @mbggenerated Mon Feb 24 23:21:02 CST 2014
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user_info.CREATE_DATE
     *
     * @mbggenerated Mon Feb 24 23:21:02 CST 2014
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user_info.ID
     *
     * @return the value of tbl_user_info.ID
     *
     * @mbggenerated Mon Feb 24 23:21:02 CST 2014
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user_info.ID
     *
     * @param id the value for tbl_user_info.ID
     *
     * @mbggenerated Mon Feb 24 23:21:02 CST 2014
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user_info.USERNAME
     *
     * @return the value of tbl_user_info.USERNAME
     *
     * @mbggenerated Mon Feb 24 23:21:02 CST 2014
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user_info.USERNAME
     *
     * @param username the value for tbl_user_info.USERNAME
     *
     * @mbggenerated Mon Feb 24 23:21:02 CST 2014
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user_info.PASSWORD
     *
     * @return the value of tbl_user_info.PASSWORD
     *
     * @mbggenerated Mon Feb 24 23:21:02 CST 2014
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user_info.PASSWORD
     *
     * @param password the value for tbl_user_info.PASSWORD
     *
     * @mbggenerated Mon Feb 24 23:21:02 CST 2014
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user_info.CREATE_DATE
     *
     * @return the value of tbl_user_info.CREATE_DATE
     *
     * @mbggenerated Mon Feb 24 23:21:02 CST 2014
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user_info.CREATE_DATE
     *
     * @param createDate the value for tbl_user_info.CREATE_DATE
     *
     * @mbggenerated Mon Feb 24 23:21:02 CST 2014
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}