package com.ezok.mapper;

import com.ezok.model.AdminInfo;
import com.ezok.model.AdminInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdminInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_admin_info
     *
     * @mbggenerated Sun Feb 16 19:16:26 CST 2014
     */
    int countByExample(AdminInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_admin_info
     *
     * @mbggenerated Sun Feb 16 19:16:26 CST 2014
     */
    int deleteByExample(AdminInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_admin_info
     *
     * @mbggenerated Sun Feb 16 19:16:26 CST 2014
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_admin_info
     *
     * @mbggenerated Sun Feb 16 19:16:26 CST 2014
     */
    int insert(AdminInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_admin_info
     *
     * @mbggenerated Sun Feb 16 19:16:26 CST 2014
     */
    int insertSelective(AdminInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_admin_info
     *
     * @mbggenerated Sun Feb 16 19:16:26 CST 2014
     */
    List<AdminInfo> selectByExample(AdminInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_admin_info
     *
     * @mbggenerated Sun Feb 16 19:16:26 CST 2014
     */
    AdminInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_admin_info
     *
     * @mbggenerated Sun Feb 16 19:16:26 CST 2014
     */
    int updateByExampleSelective(@Param("record") AdminInfo record, @Param("example") AdminInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_admin_info
     *
     * @mbggenerated Sun Feb 16 19:16:26 CST 2014
     */
    int updateByExample(@Param("record") AdminInfo record, @Param("example") AdminInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_admin_info
     *
     * @mbggenerated Sun Feb 16 19:16:26 CST 2014
     */
    int updateByPrimaryKeySelective(AdminInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_admin_info
     *
     * @mbggenerated Sun Feb 16 19:16:26 CST 2014
     */
    int updateByPrimaryKey(AdminInfo record);
}