package com.ezok.mapper;

import com.ezok.model.CategoryInfo;
import com.ezok.model.CategoryInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CategoryInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_category_info
     *
     * @mbggenerated Tue Feb 18 09:43:03 CST 2014
     */
    int countByExample(CategoryInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_category_info
     *
     * @mbggenerated Tue Feb 18 09:43:03 CST 2014
     */
    int deleteByExample(CategoryInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_category_info
     *
     * @mbggenerated Tue Feb 18 09:43:03 CST 2014
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_category_info
     *
     * @mbggenerated Tue Feb 18 09:43:03 CST 2014
     */
    int insert(CategoryInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_category_info
     *
     * @mbggenerated Tue Feb 18 09:43:03 CST 2014
     */
    int insertSelective(CategoryInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_category_info
     *
     * @mbggenerated Tue Feb 18 09:43:03 CST 2014
     */
    List<CategoryInfo> selectByExample(CategoryInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_category_info
     *
     * @mbggenerated Tue Feb 18 09:43:03 CST 2014
     */
    CategoryInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_category_info
     *
     * @mbggenerated Tue Feb 18 09:43:03 CST 2014
     */
    int updateByExampleSelective(@Param("record") CategoryInfo record, @Param("example") CategoryInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_category_info
     *
     * @mbggenerated Tue Feb 18 09:43:03 CST 2014
     */
    int updateByExample(@Param("record") CategoryInfo record, @Param("example") CategoryInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_category_info
     *
     * @mbggenerated Tue Feb 18 09:43:03 CST 2014
     */
    int updateByPrimaryKeySelective(CategoryInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_category_info
     *
     * @mbggenerated Tue Feb 18 09:43:03 CST 2014
     */
    int updateByPrimaryKey(CategoryInfo record);
}