package com.ezok.mapper;

import com.ezok.model.NavInfo;
import com.ezok.model.NavInfoExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface NavInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_nav_info
     *
     * @mbggenerated Sun Feb 16 15:31:59 CST 2014
     */
    int countByExample(NavInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_nav_info
     *
     * @mbggenerated Sun Feb 16 15:31:59 CST 2014
     */
    int deleteByExample(NavInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_nav_info
     *
     * @mbggenerated Sun Feb 16 15:31:59 CST 2014
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_nav_info
     *
     * @mbggenerated Sun Feb 16 15:31:59 CST 2014
     */
    int insert(NavInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_nav_info
     *
     * @mbggenerated Sun Feb 16 15:31:59 CST 2014
     */
    int insertSelective(NavInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_nav_info
     *
     * @mbggenerated Sun Feb 16 15:31:59 CST 2014
     */
    List<NavInfo> selectByExample(NavInfoExample example);

    List<NavInfo> selectByExample(NavInfoExample example, RowBounds rowBounds);

    List<NavInfo> getNavInfoVoByParentCate(String categoryNo, RowBounds rowBounds);

    Integer countNavInfoVoByParentCate(String categoryNo);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_nav_info
     *
     * @mbggenerated Sun Feb 16 15:31:59 CST 2014
     */
    NavInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_nav_info
     *
     * @mbggenerated Sun Feb 16 15:31:59 CST 2014
     */
    int updateByExampleSelective(@Param("record") NavInfo record, @Param("example") NavInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_nav_info
     *
     * @mbggenerated Sun Feb 16 15:31:59 CST 2014
     */
    int updateByExample(@Param("record") NavInfo record, @Param("example") NavInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_nav_info
     *
     * @mbggenerated Sun Feb 16 15:31:59 CST 2014
     */
    int updateByPrimaryKeySelective(NavInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_nav_info
     *
     * @mbggenerated Sun Feb 16 15:31:59 CST 2014
     */
    int updateByPrimaryKey(NavInfo record);
}