package com.ezok.mapper;

import com.ezok.model.NavRelArticle;
import com.ezok.model.NavRelArticleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NavRelArticleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_rel_nav_article
     *
     * @mbggenerated Thu Apr 17 22:57:42 CST 2014
     */
    int countByExample(NavRelArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_rel_nav_article
     *
     * @mbggenerated Thu Apr 17 22:57:42 CST 2014
     */
    int deleteByExample(NavRelArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_rel_nav_article
     *
     * @mbggenerated Thu Apr 17 22:57:42 CST 2014
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_rel_nav_article
     *
     * @mbggenerated Thu Apr 17 22:57:42 CST 2014
     */
    int insert(NavRelArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_rel_nav_article
     *
     * @mbggenerated Thu Apr 17 22:57:42 CST 2014
     */
    int insertSelective(NavRelArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_rel_nav_article
     *
     * @mbggenerated Thu Apr 17 22:57:42 CST 2014
     */
    List<NavRelArticle> selectByExample(NavRelArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_rel_nav_article
     *
     * @mbggenerated Thu Apr 17 22:57:42 CST 2014
     */
    NavRelArticle selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_rel_nav_article
     *
     * @mbggenerated Thu Apr 17 22:57:42 CST 2014
     */
    int updateByExampleSelective(@Param("record") NavRelArticle record, @Param("example") NavRelArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_rel_nav_article
     *
     * @mbggenerated Thu Apr 17 22:57:42 CST 2014
     */
    int updateByExample(@Param("record") NavRelArticle record, @Param("example") NavRelArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_rel_nav_article
     *
     * @mbggenerated Thu Apr 17 22:57:42 CST 2014
     */
    int updateByPrimaryKeySelective(NavRelArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_rel_nav_article
     *
     * @mbggenerated Thu Apr 17 22:57:42 CST 2014
     */
    int updateByPrimaryKey(NavRelArticle record);
}