package com.ezok.mapper;

import com.ezok.model.NavWeek;
import com.ezok.model.NavWeekExample;

import java.util.List;

import com.ezok.model.NavWeekExtend;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface NavWeekMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_nav_week
     *
     * @mbggenerated Wed Mar 26 13:14:41 CST 2014
     */
    int countByExample(NavWeekExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_nav_week
     *
     * @mbggenerated Wed Mar 26 13:14:41 CST 2014
     */
    int deleteByExample(NavWeekExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_nav_week
     *
     * @mbggenerated Wed Mar 26 13:14:41 CST 2014
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_nav_week
     *
     * @mbggenerated Wed Mar 26 13:14:41 CST 2014
     */
    int insert(NavWeek record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_nav_week
     *
     * @mbggenerated Wed Mar 26 13:14:41 CST 2014
     */
    int insertSelective(NavWeek record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_nav_week
     *
     * @mbggenerated Wed Mar 26 13:14:41 CST 2014
     */
    List<NavWeek> selectByExample(NavWeekExample example);

    List<NavWeek> selectByExample(NavWeekExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_nav_week
     *
     * @mbggenerated Wed Mar 26 13:14:41 CST 2014
     */
    NavWeek selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_nav_week
     *
     * @mbggenerated Wed Mar 26 13:14:41 CST 2014
     */
    int updateByExampleSelective(@Param("record") NavWeek record, @Param("example") NavWeekExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_nav_week
     *
     * @mbggenerated Wed Mar 26 13:14:41 CST 2014
     */
    int updateByExample(@Param("record") NavWeek record, @Param("example") NavWeekExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_nav_week
     *
     * @mbggenerated Wed Mar 26 13:14:41 CST 2014
     */
    int updateByPrimaryKeySelective(NavWeek record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_nav_week
     *
     * @mbggenerated Wed Mar 26 13:14:41 CST 2014
     */
    int updateByPrimaryKey(NavWeek record);

    List<NavWeekExtend> getNavWeekExtendList(RowBounds rowBounds);

    Integer countNavWeekExtendList();
}