package com.ezok.mapper;

import com.ezok.model.UserInfo;
import com.ezok.model.UserInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user_info
     *
     * @mbggenerated Mon Feb 24 23:21:02 CST 2014
     */
    int countByExample(UserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user_info
     *
     * @mbggenerated Mon Feb 24 23:21:02 CST 2014
     */
    int deleteByExample(UserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user_info
     *
     * @mbggenerated Mon Feb 24 23:21:02 CST 2014
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user_info
     *
     * @mbggenerated Mon Feb 24 23:21:02 CST 2014
     */
    int insert(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user_info
     *
     * @mbggenerated Mon Feb 24 23:21:02 CST 2014
     */
    int insertSelective(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user_info
     *
     * @mbggenerated Mon Feb 24 23:21:02 CST 2014
     */
    List<UserInfo> selectByExample(UserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user_info
     *
     * @mbggenerated Mon Feb 24 23:21:02 CST 2014
     */
    UserInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user_info
     *
     * @mbggenerated Mon Feb 24 23:21:02 CST 2014
     */
    int updateByExampleSelective(@Param("record") UserInfo record, @Param("example") UserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user_info
     *
     * @mbggenerated Mon Feb 24 23:21:02 CST 2014
     */
    int updateByExample(@Param("record") UserInfo record, @Param("example") UserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user_info
     *
     * @mbggenerated Mon Feb 24 23:21:02 CST 2014
     */
    int updateByPrimaryKeySelective(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user_info
     *
     * @mbggenerated Mon Feb 24 23:21:02 CST 2014
     */
    int updateByPrimaryKey(UserInfo record);
}